# Architecture
arch: FC

# ===== Dataset ===== #
data: /home/rebekka/Documents/GitHub/data #/mnt
set: MNIST
name: fc_kn_unsigned

# ===== Learning Rate Policy ======== #
optimizer: sgd
lr: 0.1
lr_policy: cosine_lr

# ===== Network training config ===== #
epochs: 100
weight_decay: 0.0001
momentum: 0.9
batch_size: 128

# ===== Sparsity =========== #
conv_type: SubnetConv
bn_type: NonAffineBatchNorm
freeze_weights: True
prune_rate: 0.01
init: kaiming_normal
scale_fan: False #True

# ===== Hardware setup ===== #
workers: 4
 
